spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/resources/, classpath:/static/
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  session:
    timeout: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.114.62.11:3306/learnhub
    username: root
    password: www.Aliyun.com
    hikari:
      maxLifetime: 60000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      auto-commit: true
      connection-timeout: 15000

  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 需要登录才能进行操作的请求uri
FilterURI: "/profile/"



